- name: Create Network Security Group that allows SSH
  azure_rm_securitygroup:
    resource_group: "{{ infrarg }}"
    name: "{{ infransg }}"
    rules:
      - name: SSH
        protocol: Tcp
        destination_port_range: 22
        access: Allow
        priority: 1001
        direction: Inbound