- name: Create resource group "{{ infrarg }}"
  azure_rm_resourcegroup:
    name: "{{ infrarg }}"
    location: "{{ location }}"
  register: outrg

- debug:
    msg: "{{ outrg }}"
  when: outrg

- name: Create DR resource group "{{ infrargdr }}"
  azure_rm_resourcegroup:
    name: "{{ infrargdr }}"
    location: "{{ locationdr }}"
  register: outrgdr

- debug:
    msg: "{{ outrgdr }}"
  when: outrgdr