- name: Create diagnoistics storage account for VM
  azure_rm_storageaccount:
    name: "{{ diagaccount }}"
    resource_group: "{{ infrarg }}"
    location: "{{ location }}"
    account_type: "{{ acc_type }}"
  register: diagacc

- debug:
    msg: "{{ diagacc }}"
  when: diagacc