- name: Create Network Security Group "{{ infransg }}" that allows SSH
  azure_rm_securitygroup:
    resource_group: "{{ infrarg }}"
    name: "{{ infransg }}"
    rules:
      - name: SSH
        protocol: Tcp
        destination_port_range: 22
        access: Allow
        priority: 1001
        direction: Inbound
      - name: RDP
        protocol: Tcp
        destination_port_range: 3389
        access: Allow
        priority: 1002
        direction: Inbound
  register: outnsg

- debug:
    msg: "{{ outnsg }}"
  when: outnsg

- name: Create DR Network Security Group "{{ infransgdr }}" that allows SSH
  azure_rm_securitygroup:
    resource_group: "{{ infrargdr }}"
    name: "{{ infransgdr }}"
    rules:
      - name: SSH
        protocol: Tcp
        destination_port_range: 22
        access: Allow
        priority: 1001
        direction: Inbound
      - name: RDP
        protocol: Tcp
        destination_port_range: 3389
        access: Allow
        priority: 1002
        direction: Inbound

  register: outnsgdr

- debug:
    msg: "{{ outnsgdr }}"
  when: outnsgdr
